# Generated by Django 4.1.3 on 2022-11-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_alter_userprofile_auth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default='no', max_length=100),
            preserve_default=False,
        ),
    ]
